version: '2'
services:
  database:
    build: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myPassword2
  appswift:
    build: server
    depends_on: [database]
    links:
      - database
    ports:
      - "8080:8080"
    environment:
      DATABASE_NAME: test2
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: myPassword2
